export default {
  // Repositories
  STORY_REPOSITORY: Symbol('STORY_REPOSITORY'),
  CHAPTER_REPOSITORY: Symbol('CHAPTER_REPOSITORY'),

  // Mappers
  STORY_MAPPER: Symbol('STORY_MAPPER'),
  CHAPTER_MAPPER: Symbol('CHAPTER_MAPPER'),

  // Models
  STORY_MODEL: Symbol('STORY_MODEL'),
  CHAPTER_MODEL: Symbol('CHAPTER_MODEL'),

  // USE CASES - STORIES
  CREATE_STORY: Symbol('CREATE_STORY'),
  UPDATE_STORY: Symbol('UPDATE_STORY'),
  FIND_ONE_STORY: Symbol('FIND_ONE_STORY'),
  FIND_STORIES: Symbol('FIND_STORIES'),
  DELETE_STORY: Symbol('DELETE_STORY'),

  // USE CASES - Chapters
  CREATE_CHAPTER: Symbol('CREATE_CHAPTER'),
  UPDATE_CHAPTER: Symbol('UPDATE_CHAPTER'),
  FIND_ONE_CHAPTER: Symbol('FIND_ONE_CHAPTER'),
  FIND_CHAPTERS: Symbol('FIND_CHAPTERS'),
  DELETE_CHAPTER: Symbol('DELETE_CHAPTER')
};
